services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: metrinomicon_be
    ports:
      - "${API_PORT}:${API_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: metrinomicon_fe
    env_file: "./frontend/.env"
    ports:
      - "3000:3000"
